### ISSUE TITLE
Inkonsistent sequence for `generate_recodes`

### ISSUE THREAD

**Issue by sjPlot** [tadaadata/tadaatoolbox#1]
When I use `generate_recodes`, the first group has more values than the following groups:

    generate_recodes(1, 20, 5)
    [1] "1:6='1-6'; 7:11='7-11'; 11:16='11-16'; 17:21='17-21'"

1-6 are 6 values, 7-11 are 5 values. I would expect a sequence like 1-5, 6-10, 11-15 etc.

**Comment by sjPlot** [comment]
(same applies to `interval_labels`)

**Comment by jemus42** [comment]
Damn, I knew they were coming back to bite me.  
They were only written as a quick hack for a one-time thing and I figured I might as well put them in the package, but now that I [look at them](https://github.com/tadaadata/tadaatoolbox/blob/master/R/recode_helpers.R#L52-L82), I might have to either rework them completely or scratch them altogether.  

I'll try to figure something out though.

**Comment by sjPlot** [comment]
It's indeed tricky, and I have also tried a lot to find a solution for `sjmisc::group_var` and `sjmisc::group_labels`.

    sjmisc::group_labels(c(1:20), groupsize = "auto", groupcount = 4)
    [1] "1-5"   "6-10"  "11-15" "16-20"

This works now, but starting from 0:20, another group is added, although group count is set to 4 - this is, because I assume integer values, thus 21 values can't be divided into 4 groups.

    sjmisc::group_labels(c(0:20), groupsize = "auto", groupcount = 4)
    [1] "0-4"   "5-9"   "10-14" "15-19" "20-24"

**Comment by MarauderPixie** [comment]
Or not. At least not `interval_labels`. m(

**Comment by sjPlot** [comment]
FYI, I added a similar function to my sjmisc-package, which generates recodes patterns for the `rec` function: https://github.com/sjPlot/sjmisc/blob/master/R/rec_pattern.R

Now your solution works, but maybe it's of interest for you how my solution looks like... A little different approach, also due to different requirements.
