### ISSUE TITLE
Random effects from sjp.glmer different from ranef

### ISSUE THREAD

**Issue by CJustice77** [tadaadata/tadaatoolbox#23]
Hi there. I'm trying to understand the output from the sjp.glmer function, and why the values differ from those produced by the ranef function. I like the look of the random effects plot generated by sjp.glmer but I don't understand the output and couldn't find documentation to clarify. Here's some example code from the sjPlot web page:

# create binary response
sleepstudy$Reaction.dicho <- 
  dicho(sleepstudy$Reaction, dich.by = "median")
# fit model
fit <- glmer(Reaction.dicho ~ Days + (Days | Subject),
             sleepstudy, family = binomial("logit"))

sjp.glmer(fit, sort.est = "(Intercept)", y.offset = .4)

# compare results from sjp.glmer with intercept values from ranef
ranef(fit)

It appears that the values from sjp.glmer are reported in log space, and therefore they are equal to  exp(ranef(fit)$Subject[,1])

However, the inverse of the logit link function is exp(logit)/(1+exp(logit)), not exp(logit). Why then are the data plotted this way? Is this an error?

Thanks for your time and help.

Sincerely,

Casey Justice

**Comment by jemus42** [comment]
Uhm, I don't know the `ranef`-function, and for `sjp.glmer` you're probably looking for [sjPlot](https://github.com/sjPlot/devel), because neither I nor this package have anything to do with sjPlot (apart from using it for some parts).

**Comment by CJustice77** [comment]
Thank you. I'm new to GitHub and posted this issue to the wrong repository somehow. My apologies.
