### ISSUE TITLE
Undocumented arguments in `tadaa_one_sample`

### ISSUE THREAD

**Issue by nutterb** [tadaadata/tadaatoolbox#30]
While doing reverse dependency checks, I encountered a warning 

> Undocumented arguments in documentation object 'tadaa_one_sample'
  'print'

Looking at the [source code](https://github.com/tadaadata/tadaatoolbox/blob/master/R/tadaa_one_sample.R), it looks like `print` and `conf.level` are both undocumented in your master branch.  

Thanks

**Comment by jemus42** [comment]
Sorry for the inconvenience, I don't know how we missed that as no checks complained. Fixing it now.
