### ISSUE TITLE
effect sizes: odds ratios for nominal data

### ISSUE THREAD

**Issue by MarauderPixie** [tadaadata/tadaatoolbox#6]
well, pretty much what it says:
add odds ratios (with confidence intervals) to categorical data

**Comment by jemus42** [comment]
Something like `effect_size_t` then, but for a `table` of two nominal vectors?

**Comment by MarauderPixie** [comment]
Quite like that. I thought of something like `OR (conf.low - conf.high)`, such as `1.12 (0.87 - 1.37)`.

**Comment by jemus42** [comment]
For the output? Why not have it output a `data.frame` with `y, ymin, ymax` so it's easy to use in plots á la `stats_summary`? Either way, I'd say the output should be as close to tidy as possible.

**Comment by MarauderPixie** [comment]
Fair enough, but maybe add an `output = c("tidy", "text")` argument. My thinking was to make it usable in running text for writing reports or the like, since ORs are so easy to interpret.

**Comment by jemus42** [comment]
Huh, options for easy, non-formatted inline-display would actually be kind of nice in general.

**Comment by sjPlot** [comment]
You may look at https://github.com/sjPlot/esc/blob/master/R/esc_2x2.R to get that. Upper and lower CI are simply:

```
# 95% confidence interval
lower_d <- function(d, v) d - 1.959964 * sqrt(v)
upper_d <- function(d, v) d + 1.959964 * sqrt(v)
```

**Comment by jemus42** [comment]
I think I'll leave that for now, but in the long run there's probably going to be some simple wrapper for one or the other `esc` function.
