### ISSUE TITLE
Add tadaa_z.test

### ISSUE THREAD

**Issue by jemus42** [tadaadata/tadaatoolbox#8]
Since base R doesn't even have a function for the z-test (presumably since it's basically trivial), it would probably be a nice addition, at least for teaching and demonstration purposes.  

The output should look like the one-sample case of `t.test` put through `broom::tidy`.

Come to think of it, `tadaa_t.test` can't handle one-sample tests since it's hardcoded to expect a binary group variable, so maybe we could instead implement a dedicated function for one-sample tests that either performs a z- or a t-test depending on whether or not a σ is provided.

So… thoughts?

**Comment by jemus42** [comment]
Current train of thought:  

Add a `tadaa_one.sample()` function that performs z- or t-test depending on whether or not a `sigma` argument is provided.  
*Should* be relatively straight forward.

**Comment by jemus42** [comment]
For the confidence intervals, I added a basic `confint_norm` – Maybe it's because it's late but I need someone to tell me that I did this right m) @MarauderPixie

**Comment by MarauderPixie** [comment]
Looking good, way to go! :+1:
